name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ১) কোড ক্লোন করুন
      - name: Checkout code
        uses: actions/checkout@v3

      # ২) Node.js সেটআপ (v3 এ ক্যাশ অটো‑ম্যানেেজ)
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'          # ~/.npm ক্যাশ হবে

      # ৩) ডিপেন্ডেন্সি ইন্সটল
      - name: Install dependencies
        run: npm install

      # ৪) অ্যাপ স্টার্ট (আপনার স্ক্রিপ্ট অনুযায়ী)
      - name: Start application
        run: npm start
